# Generated by Django 2.1 on 2018-08-29 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='School Name')),
                ('max_students', models.PositiveIntegerField(verbose_name='Maximum Number of Students')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('student_id', models.CharField(max_length=20, verbose_name='Student ID')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.School', verbose_name='Student School')),
            ],
        ),
    ]
